export const GET_USER_SUMMARY = "GET_USER_SUMMARY";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const POST_USER_SUMMARY: string = "POST_USER_SUMMARY";
export const POST_USER_SUCCESS: string = "POST_USER_SUCCESS";

export const PUT_USER_SUMMARY = "PUT_USER_SUMMARY";
export const PUT_USER_SUCCESS = "PUT_USER_SUCCESS";

export const DELETE_USER_SUMMARY = "DELETE_USER_SUMMARY";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
